<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<h1>Главная</h1>
<a href="/reg">Регистрация</a>
<a href="/log">Авторизация</a>

<table>
    <thead>
    <td>id</td>
    <td>текст</td>
    <td>Автор</td>
    </thead>
    <?php foreach ($items as $item):?>
    <tbody>

    <td><?=$item['id']?></td>
    <td><?=$item['text']?></td>
    <td><?=$item['users_id']?></td>

    <?php endforeach;?>
    </tbody>
</table>
</body>
</html>
